<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer_add</title>
</head>
<body>
    <form action="index.php?action=add" method="post" enctype="multipart/form-data">
        <label for="name">Name</label>
        <input type="text" name="name" required>
        <label for="avatar">Avatar</label>
        <input type="file" name="avatar">
        <label for="email">Email</label>
        <input type="email" name="email" id="" required>
        <label for="phone">Phone</label>
        <input type="number" name="phone" id="" required>
        <label for="address">Address</label>
        <input type="text" name="address" id="" required>
        <label for="gender">Gender</label>
        <select name="gender" id="" required>
            <option value="male">male</option>
            <option value="female">female</option>
            <option value="other">other</option>
        </select>
        <label for="status">Status</label>
        <select name="status" id="" required>
            <option value="1">active</option>
            <option value="0">inactive</option>
        </select>
        <button type="submit">Add</button>
    </form>
</body>
</html>