<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <form action="" method="get">
        <label for="search">Search</label>
        <input type="hidden" name="action" value="search">
        <input type="text" name="search" placeholder="Search name, phone, email" value="<?= htmlspecialchars(
            $data['search'],
        ) ?>">
        <button type="submit">Search</button>
        <a href="/">Reset</a>
    </form>
    
    <table>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>avatar</th>
            <th>email</th>
            <th>phone</th>
            <th>address</th>
            <th>gender</th>
            <th>status</th>
            <th>created_at</th>
            <th><a href="index.php?action=add">Add</a></th>
        </tr>
        <?php foreach ($data['customers'] as $customer): ?>
            <tr>
                <td><?= $customer['id'] ?></td>
                <td><?= $customer['name'] ?></td>
                <td>
                    <?php if (!empty($customer['avatar'])): ?>
                        <img src="<?= $customer[
                            'avatar'
                        ] ?>" width="80" height="80" style="object-fit:cover; border-radius:50%" >
                    <?php endif; ?>
                </td>
                <td><?= $customer['email'] ?></td>
                <td><?= $customer['phone'] ?></td>
                <td><?= $customer['address'] ?></td>
                <td><?= $customer['gender'] ?></td>
                <td><?= $customer['status'] ?></td>
                <td><?= $customer['created_at'] ?></td>
                <td>
                    <a href="index.php?action=edit&id=<?= $customer['id'] ?>">Edit</a>
                    <a onclick="return confirm('Do you want to delete ?')" href="index.php?action=delete&id=<?= $customer[
                        'id'
                    ] ?>">Delete</a>
                    <a href="index.php?action=view&id=<?= $customer['id'] ?>">View</a>
                </td>
            </tr>
        <?php endforeach; ?>    
    </table>
</body>
</html>

