<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer_add</title>
</head>
<body>
    <form action="index.php?action=edit&id=<?= $data['customer'][
        'id'
    ] ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="id" value="<?= $data['customer']['id'] ?>">
        <label for="name">Name</label>
        <input type="text" name="name" value="<?= $data['customer']['name'] ?>" required>
        <label for="avatar">Avatar</label>
        <?php if (!empty($data['customer']['avatar'])): ?>
            <img src="<?= $data['customer']['avatar'] ?>" width="100">
        <?php endif; ?>
        <input type="file" name="avatar">
        <label for="email">Email</label>
        <input type="email" name="email" id="" value="<?= $data['customer']['email'] ?>" required>
        <label for="phone">Phone</label>
        <input type="number" name="phone" id="" value="<?= $data['customer']['phone'] ?>" required>
        <label for="address">Address</label>
        <input type="text" name="address" id="" value="<?= $data['customer'][
            'address'
        ] ?>" required>
        <label for="gender">Gender</label>
        <select name="gender" id="" required>
            <option value="male" <?= $data['customer']['gender'] == 'male'
                ? 'selected'
                : '' ?> >male</option>
            <option value="female" <?= $data['customer']['gender'] == 'female'
                ? 'selected'
                : '' ?> >female</option>
            <option value="other" <?= $data['customer']['gender'] == 'other'
                ? 'selected'
                : '' ?> >other</option>
        </select>
        <label for="status">Status</label>
        <select name="status" id="" selected required>
            <option value="1" <?= $data['customer']['status'] === '1'
                ? 'selected'
                : '' ?> >active</option>
            <option value="0" <?= $data['customer']['status'] === '0'
                ? 'selected'
                : '' ?> >inactive</option>
        </select>
        <button type="submit">Update</button>
    </form>
</body>
</html>